import { parseCsv } from './csv.js';
import { canonicalEmployeeName } from './employees.js';
import { canonicalMetricId } from './metrics.js';
import type { DailyFactRow } from './daily-facts.js';

export type ReconciliationStatus = 'PASS' | 'MISMATCH' | 'TRUE_NO_DAILY_DATA';

export interface ReconciliationRow {
  month: string;
  employeeName: string;
  metricId: string;
  monthlySource: number;
  dailySum: number | null;
  status: ReconciliationStatus;
}

/**
 * Recomputes reconciliation using the corrected canonical metric map — the
 * bundled t2_legacy_reconciliation.csv itself was generated by matching
 * raw literal strings, which is exactly the bug this recomputation fixes
 * for Combo/Sim (and would fix for any other future RU/EN literal split).
 */
export function recomputeReconciliation(
  monthlyActualsSourceCsv: string,
  dailyFacts: DailyFactRow[]
): ReconciliationRow[] {
  const dailySumByKey = new Map<string, number>();
  for (const fact of dailyFacts) {
    const month = fact.date.slice(0, 7);
    for (const [metricId, value] of Object.entries(fact.metrics)) {
      const k = `${month}|${fact.employeeName}|${metricId}`;
      dailySumByKey.set(k, (dailySumByKey.get(k) ?? 0) + value);
    }
  }

  const rows: ReconciliationRow[] = [];
  const unmapped: string[] = [];
  for (const row of parseCsv(monthlyActualsSourceCsv)) {
    if (row.record_type !== 'monthly_actual_source') continue;
    const employeeName = canonicalEmployeeName(row.employee_name);
    const month = row.month;
    const metricId = canonicalMetricId(row.metric);
    if (!metricId) {
      unmapped.push(row.metric);
      continue;
    }
    const monthlySource = Number(row.value);
    if (!Number.isFinite(monthlySource)) continue;
    const k = `${month}|${employeeName}|${metricId}`;
    const dailySum = dailySumByKey.has(k) ? dailySumByKey.get(k)! : null;
    let status: ReconciliationStatus;
    if (dailySum === null) {
      status = 'TRUE_NO_DAILY_DATA';
    } else if (Math.abs(dailySum - monthlySource) < 0.005) {
      status = 'PASS';
    } else {
      status = 'MISMATCH';
    }
    rows.push({ month, employeeName, metricId, monthlySource, dailySum, status });
  }
  if (unmapped.length > 0) {
    throw new Error(
      `monthly_actuals_source.csv contains ${unmapped.length} rows with unmapped metric literals: ${[...new Set(unmapped)].join(', ')}`
    );
  }
  return rows;
}
